name: Workflow CI MLProject

on:
  push:
    paths:
      - 'MLProject/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Set Up Job (Otomatis dibuat oleh GitHub)

    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        python --version
        pip --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy

    - name: Run mlflow project
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        cd MLProject
        # Mengambil ID terbaru dari folder mlruns/0 (mengabaikan file meta.yaml)
        RUN_ID=$(ls -t mlruns/0 | grep -v meta.yaml | head -n 1)
        echo "Run ID terbaru adalah: $RUN_ID"
        # Menyimpan RUN_ID ke environment variable GitHub agar bisa dipakai di step selanjutnya
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Install Python dependencies
      run: |
        # Step ini mungkin dulunya untuk GDrive API, kita isi dengan upgrade setuptools
        pip install --upgrade setuptools wheel

    - name: Upload to Github
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # Kita mengunggah folder mlruns yang berisi hasil model dari run ID terbaru
        git add MLProject/mlruns/
        git commit -m "Upload model artifact (Run ID: ${{ env.RUN_ID }}) to GitHub" || echo "No changes to commit"
        git push

    - name: Build Docker Model
      run: |
        cd MLProject
        sed -i '/channels:/a \  - nodefaults' "mlruns/0/${{ env.RUN_ID }}/artifacts/model/conda.yaml"
        mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" -n housing-model:latest --env-manager=conda

    - name: Log in Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: |
        docker tag housing-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/housing-model:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/housing-model:latest

    # Post steps dan Complete job (Otomatis dibuat oleh GitHub di akhir)